name: publish-packages

on:
  push:
    branches:
      - ci/publish-packages

jobs:
#  version:
#    name: Bump version and push tag
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Bump version and push tag
#        uses: hennejg/github-tag-action@v4.2.4
#        with:
#          default_bump: patch
#          release_branches: master
#          github_token: ${{ secrets.RADIXBOT_GITHUB_REPO_PACKAGES_TOKEN }}
  build:
    runs-on: ubuntu-latest
    name: Publish mvn packages
#    needs: version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Restore Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: restore
      - name: Build
        run: |
          git tag v0.1.0
          ./mvnw -Dversioning.preferTags=true clean package
          ls -l target
          ./mvnw -Dversioning.preferTags=true deploy
      - name: Save Maven cache
        uses: skjolber/maven-cache-github-action@v1
        with:
          step: save

