name: publish-packages

on:
  push:
    branches:
      - ci/publish-packages

jobs:
#  version:
#    name: Bump version and push tag
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Bump version and push tag
#        uses: hennejg/github-tag-action@v4.2.4
#        with:
#          default_bump: patch
#          release_branches: master
#          github_token: ${{ secrets.RADIXBOT_GITHUB_REPO_PACKAGES_TOKEN }}
  build:
    runs-on: ubuntu-latest
    name: Publish mvn packages
#    needs: version
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: |
          git tag v0.1.0
          ./mvnw -Dversioning.preferTags=true clean package
          ls -l build/libs
          ./mvnw -Dversioning.preferTags=true deploy
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

